[package]
name = "decentralized_checkpoint_sync_client"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
decentralized_checkpoint_sync = { workspace = true }
eth2 = { workspace = true }
slot_clock = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
types = { workspace = true }

[dev-dependencies]
bls = { workspace = true }
merkle_proof = { workspace = true }
mockito = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
tree_hash = { workspace = true }
