[package]
name = "decentralized_checkpoint_sync"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bls = { workspace = true }
merkle_proof = { workspace = true }
safe_arith = { workspace = true }
thiserror = { workspace = true }
tree_hash = { workspace = true }
types = { workspace = true }
