FROM debian:buster-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
  libssl-dev \
  ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
COPY target/x86_64-unknown-linux-gnu/release/lighthouse /usr/local/bin/lighthouse
