-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [state_processing]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace state_processing

/-- [state_processing::builder_payment_window::WindowError]
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 30:0-35:1
    Visibility: public -/
@[discriminant isize]
inductive builder_payment_window.WindowError where
| Bounds : builder_payment_window.WindowError
| Arith : builder_payment_window.WindowError

/-- [state_processing::builder_payment_window::PendingWithdrawal]
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 40:0-44:1
    Visibility: public -/
structure builder_payment_window.PendingWithdrawal where
  fee_recipient : Array Std.U8 20#usize
  amount : Std.U64
  builder_index : Std.U64

/-- [state_processing::builder_payment_window::{impl core::default::Default for state_processing::builder_payment_window::PendingWithdrawal}::default]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 39:44-39:51
    Visibility: public -/
def builder_payment_window.PendingWithdrawal.Insts.CoreDefaultDefault.default
  : Result builder_payment_window.PendingWithdrawal := do
  let a ← core.default.DefaultArray.default 20#usize core.default.DefaultU8
  ok
    {
      fee_recipient := a,
      amount := (core.default.DefaultU64.default),
      builder_index := (core.default.DefaultU64.default)
    }

/-- [state_processing::builder_payment_window::PendingPayment]
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 48:0-52:1
    Visibility: public -/
structure builder_payment_window.PendingPayment where
  weight : Std.U64
  withdrawal : builder_payment_window.PendingWithdrawal
  proposer_index : Std.U64

/-- [state_processing::builder_payment_window::{impl core::default::Default for state_processing::builder_payment_window::PendingPayment}::default]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 47:44-47:51
    Visibility: public -/
def builder_payment_window.PendingPayment.Insts.CoreDefaultDefault.default
  : Result builder_payment_window.PendingPayment := do
  let pw ←
    builder_payment_window.PendingWithdrawal.Insts.CoreDefaultDefault.default
  ok
    {
      weight := (core.default.DefaultU64.default),
      withdrawal := pw,
      proposer_index := (core.default.DefaultU64.default)
    }

/-- [state_processing::builder_payment_window::PaymentEpoch]
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 56:0-61:1
    Visibility: public -/
@[discriminant isize]
inductive builder_payment_window.PaymentEpoch where
| Previous : builder_payment_window.PaymentEpoch
| Current : builder_payment_window.PaymentEpoch

/-- [state_processing::builder_payment_window::payment_index]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 64:0-78:1
    Visibility: public -/
def builder_payment_window.payment_index
  (slot : Std.U64) (slots_per_epoch : Std.U64)
  (epoch : builder_payment_window.PaymentEpoch) :
  Result (core.result.Result Std.U64 builder_payment_window.WindowError)
  := do
  let o ← lift (U64.checked_rem slot slots_per_epoch)
  let r ← core.option.Option.ok_or o builder_payment_window.WindowError.Arith
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    match epoch with
    | builder_payment_window.PaymentEpoch.Previous =>
      ok (core.result.Result.Ok val)
    | builder_payment_window.PaymentEpoch.Current =>
      let o1 ← lift (U64.checked_add slots_per_epoch val)
      core.option.Option.ok_or o1 builder_payment_window.WindowError.Arith
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U64 (core.convert.FromSame builder_payment_window.WindowError)
      residual

/-- [state_processing::builder_payment_window::record_bid_payment]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 81:0-102:1
    Visibility: public -/
def builder_payment_window.record_bid_payment
  (payments : Slice builder_payment_window.PendingPayment)
  (slots_per_epoch : Std.U64) (slot : Std.U64)
  (withdrawal : builder_payment_window.PendingWithdrawal)
  (proposer_index : Std.U64) :
  Result ((core.result.Result Unit builder_payment_window.WindowError) ×
    (Slice builder_payment_window.PendingPayment))
  := do
  if withdrawal.amount > 0#u64
  then
    let r ←
      builder_payment_window.payment_index slot slots_per_epoch
        builder_payment_window.PaymentEpoch.Current
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let index ← lift (UScalar.cast .Usize val)
      let (o, get_mut_back) ←
        core.slice.Slice.get_mut (core.slice.index.SliceIndexUsizeSlice
          builder_payment_window.PendingPayment) payments index
      match o with
      | none =>
        let payments1 := get_mut_back none
        ok (core.result.Result.Err builder_payment_window.WindowError.Bounds,
          payments1)
      | some _ =>
        let payments1 :=
          get_mut_back (some { weight := 0#u64, withdrawal, proposer_index })
        ok (core.result.Result.Ok (), payments1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame builder_payment_window.WindowError)
          residual
      ok (r1, payments)
  else ok (core.result.Result.Ok (), payments)

/-- [state_processing::builder_payment_window::add_attestation_weight]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 105:0-120:1
    Visibility: public -/
def builder_payment_window.add_attestation_weight
  (payments : Slice builder_payment_window.PendingPayment) (index : Std.Usize)
  (effective_balance : Std.U64) :
  Result ((core.result.Result Unit builder_payment_window.WindowError) ×
    (Slice builder_payment_window.PendingPayment))
  := do
  let (o, get_mut_back) ←
    core.slice.Slice.get_mut (core.slice.index.SliceIndexUsizeSlice
      builder_payment_window.PendingPayment) payments index
  match o with
  | none =>
    let payments1 := get_mut_back none
    ok (core.result.Result.Err builder_payment_window.WindowError.Bounds,
      payments1)
  | some entry =>
    let o1 ← lift (U64.checked_add entry.weight effective_balance)
    match o1 with
    | none =>
      let payments1 := get_mut_back o
      ok (core.result.Result.Err builder_payment_window.WindowError.Arith,
        payments1)
    | some weight =>
      let payments1 := get_mut_back (some { entry with weight })
      ok (core.result.Result.Ok (), payments1)

/-- [state_processing::builder_payment_window::pay_on_reveal]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 129:0-149:1
    Visibility: public -/
def builder_payment_window.pay_on_reveal
  (payments : Slice builder_payment_window.PendingPayment)
  (withdrawals : alloc.vec.Vec builder_payment_window.PendingWithdrawal)
  (index : Std.Usize) :
  Result ((core.result.Result Bool builder_payment_window.WindowError) ×
    (Slice builder_payment_window.PendingPayment) × (alloc.vec.Vec
    builder_payment_window.PendingWithdrawal))
  := do
  let (o, get_mut_back) ←
    core.slice.Slice.get_mut (core.slice.index.SliceIndexUsizeSlice
      builder_payment_window.PendingPayment) payments index
  match o with
  | none =>
    let payments1 := get_mut_back none
    ok (core.result.Result.Err builder_payment_window.WindowError.Bounds,
      payments1, withdrawals)
  | some entry =>
    let entry1 ←
      builder_payment_window.PendingPayment.Insts.CoreDefaultDefault.default
    if entry.withdrawal.amount > 0#u64
    then
      let withdrawals1 ← alloc.vec.Vec.push withdrawals entry.withdrawal
      let payments1 := get_mut_back (some entry1)
      ok (core.result.Result.Ok true, payments1, withdrawals1)
    else
      let payments1 := get_mut_back (some entry1)
      ok (core.result.Result.Ok false, payments1, withdrawals)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]: loop body 0:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 168:4-173:5
    Visibility: public -/
@[rust_loop_body]
def builder_payment_window.pay_at_epoch_transition_loop0.body
  (payments : Slice builder_payment_window.PendingPayment) (quorum : Std.U64)
  (spe : Std.Usize)
  (withdrawals : alloc.vec.Vec builder_payment_window.PendingWithdrawal)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec builder_payment_window.PendingWithdrawal)
    × Std.Usize) (alloc.vec.Vec builder_payment_window.PendingWithdrawal))
  := do
  if i < spe
  then
    let pp ← Slice.index_usize payments i
    let withdrawals1 ←
      if pp.weight >= quorum
      then alloc.vec.Vec.push withdrawals pp.withdrawal
      else ok withdrawals
    let i1 ← i + 1#usize
    ok (cont (withdrawals1, i1))
  else ok (done withdrawals)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]: loop 0:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 168:4-173:5
    Visibility: public -/
@[rust_loop]
def builder_payment_window.pay_at_epoch_transition_loop0
  (payments : Slice builder_payment_window.PendingPayment)
  (withdrawals : alloc.vec.Vec builder_payment_window.PendingWithdrawal)
  (quorum : Std.U64) (spe : Std.Usize) (i : Std.Usize) :
  Result (alloc.vec.Vec builder_payment_window.PendingWithdrawal)
  := do
  loop
    (fun (withdrawals1, i1) =>
      builder_payment_window.pay_at_epoch_transition_loop0.body payments quorum
      spe withdrawals1 i1)
    (withdrawals, i)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]: loop body 1:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 177:4-180:5
    Visibility: public -/
@[rust_loop_body]
def builder_payment_window.pay_at_epoch_transition_loop1.body
  (spe : Std.Usize) (payments : Slice builder_payment_window.PendingPayment)
  (i : Std.Usize) :
  Result (ControlFlow ((Slice builder_payment_window.PendingPayment) ×
    Std.Usize) (Slice builder_payment_window.PendingPayment))
  := do
  if i < spe
  then
    let i1 ← i + spe
    let pp ← Slice.index_usize payments i1
    let s ← Slice.update payments i pp
    let i2 ← i + 1#usize
    ok (cont (s, i2))
  else ok (done payments)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]: loop 1:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 177:4-180:5
    Visibility: public -/
@[rust_loop]
def builder_payment_window.pay_at_epoch_transition_loop1
  (payments : Slice builder_payment_window.PendingPayment) (spe : Std.Usize)
  (i : Std.Usize) :
  Result (Slice builder_payment_window.PendingPayment)
  := do
  loop
    (fun (payments1, i1) =>
      builder_payment_window.pay_at_epoch_transition_loop1.body spe payments1
      i1)
    (payments, i)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]: loop body 2:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 184:4-187:5
    Visibility: public -/
@[rust_loop_body]
def builder_payment_window.pay_at_epoch_transition_loop2.body
  (len : Std.Usize) (payments : Slice builder_payment_window.PendingPayment)
  (i : Std.Usize) :
  Result (ControlFlow ((Slice builder_payment_window.PendingPayment) ×
    Std.Usize) (Slice builder_payment_window.PendingPayment))
  := do
  if i < len
  then
    let pp ←
      builder_payment_window.PendingPayment.Insts.CoreDefaultDefault.default
    let s ← Slice.update payments i pp
    let i1 ← i + 1#usize
    ok (cont (s, i1))
  else ok (done payments)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]: loop 2:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 184:4-187:5
    Visibility: public -/
@[rust_loop]
def builder_payment_window.pay_at_epoch_transition_loop2
  (payments : Slice builder_payment_window.PendingPayment) (len : Std.Usize)
  (i : Std.Usize) :
  Result (Slice builder_payment_window.PendingPayment)
  := do
  loop
    (fun (payments1, i1) =>
      builder_payment_window.pay_at_epoch_transition_loop2.body len payments1
      i1)
    (payments, i)

/-- [state_processing::builder_payment_window::pay_at_epoch_transition]:
    Source: 'consensus/state_processing/src/builder_payment_window/mod.rs', lines 154:0-190:1
    Visibility: public -/
def builder_payment_window.pay_at_epoch_transition
  (payments : Slice builder_payment_window.PendingPayment)
  (withdrawals : alloc.vec.Vec builder_payment_window.PendingWithdrawal)
  (slots_per_epoch : Std.U64) (quorum : Std.U64) :
  Result ((core.result.Result Unit builder_payment_window.WindowError) ×
    (Slice builder_payment_window.PendingPayment) × (alloc.vec.Vec
    builder_payment_window.PendingWithdrawal))
  := do
  let spe ← lift (UScalar.cast .Usize slots_per_epoch)
  let o ← lift (Usize.checked_mul spe 2#usize)
  let r ← core.option.Option.ok_or o builder_payment_window.WindowError.Arith
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i := Slice.len payments
    if i != val
    then
      ok (core.result.Result.Err builder_payment_window.WindowError.Bounds,
        payments, withdrawals)
    else
      let withdrawals1 ←
        builder_payment_window.pay_at_epoch_transition_loop0 payments
          withdrawals quorum spe 0#usize
      let payments1 ←
        builder_payment_window.pay_at_epoch_transition_loop1 payments spe
          0#usize
      let payments2 ←
        builder_payment_window.pay_at_epoch_transition_loop2 payments1 val spe
      ok (core.result.Result.Ok (), payments2, withdrawals1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let r1 ←
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Unit (core.convert.FromSame builder_payment_window.WindowError)
        residual
    ok (r1, payments, withdrawals)

end state_processing
