[package]
name = "proof_engine"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[features]
ere-verifier = ["dep:flate2", "dep:reqwest", "dep:sha2", "dep:tar"]
test-utils = []

[dependencies]
ethereum_serde_utils = { workspace = true }
ethereum_ssz = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
types = { workspace = true }

[build-dependencies]
flate2 = { version = "1", optional = true }
reqwest = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
tar = { version = "0.4", default-features = false, optional = true }

[dev-dependencies]
tree_hash = { workspace = true }
