[package]
name = "lru_cache"
version = "0.1.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition = { workspace = true }

[dependencies]
fnv = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
hashlink = { workspace = true }
lru = "0.12"
mock_instant = "0.3"
rand = "0.9"

[[bench]]
name = "lru_comparison"
harness = false
