[package]
name = "zkvm_execution_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1" #TODO(zkproofs): Remove
lru = "0.12"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "2"
types = { path = "../consensus/types" }


[dev-dependencies]
