#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled;
export DOCKER_BUILDKIT=1;
docker build --platform=local -o . git://github.com/docker/buildx;
mkdir -p ~/.docker/cli-plugins;
mv buildx ~/.docker/cli-plugins/docker-buildx;

docker version;

docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d;
docker buildx rm cross-builder;
docker buildx create --use --name cross-builder;

docker buildx inspect --bootstrap;

# Build hook to run on Docker Hub to ensure that the image is built with `PORTABLE=true`.
docker buildx build \
    --build-arg PORTABLE=true \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    --platform=linux/amd64,linux/arm64 .
