[package]
name = "lean_validator_service"
version = "0.1.0"
edition.workspace = true

[dependencies]
ethereum_ssz = "0.10.0"
ethereum_ssz_derive = "0.10.0"
futures = { workspace = true }
leansig = { git = "https://github.com/leanEthereum/leanSig" }
lean_consensus = { workspace = true }
lean_crypto = { workspace = true }
lean_forkchoice = { workspace = true }
lean_keystore = { path = "../keystore" }
lean_network = { workspace = true }
lean_store = { workspace = true }
slot_clock = { workspace = true }
store = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tree_hash = { workspace = true }
types = { workspace = true }
