[package]
name = "fast_confirmation"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
metrics = { workspace = true }
proto_array = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }

[dev-dependencies]
state_processing = { workspace = true }
