[package]
name = "lean_client"
version = "0.1.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition.workspace = true

[dependencies]
clap = { workspace = true }
clap_utils = { workspace = true }
environment = { workspace = true }
lean_attestation_service = { workspace = true }
lean_network = { workspace = true }
serde = { workspace = true }
slot_clock = { workspace = true }
task_executor = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }

