/*
 * Minimal Beacon Node API for Validator
 *
 * A minimal API specification for the beacon node, which enables a validator to connect and perform its obligations on the Ethereum 2.0 phase 0 beacon chain.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AttesterSlashings : The [`AttesterSlashing`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#attesterslashing) object from the Eth2.0 spec.

#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct AttesterSlashings {
    #[serde(rename = "attestation_1", skip_serializing_if = "Option::is_none")]
    pub attestation_1: Option<::models::IndexedAttestation>,
    #[serde(rename = "attestation_2", skip_serializing_if = "Option::is_none")]
    pub attestation_2: Option<::models::IndexedAttestation>,
}

impl AttesterSlashings {
    /// The [`AttesterSlashing`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#attesterslashing) object from the Eth2.0 spec.
    pub fn new() -> AttesterSlashings {
        AttesterSlashings {
            attestation_1: None,
            attestation_2: None,
        }
    }
}


