/*
 * Minimal Beacon Node API for Validator
 *
 * A minimal API specification for the beacon node, which enables a validator to connect and perform its obligations on the Ethereum 2.0 phase 0 beacon chain.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse200 {
    /// A boolean of whether the node is currently syncing or not.
    #[serde(rename = "is_syncing", skip_serializing_if = "Option::is_none")]
    pub is_syncing: Option<bool>,
    #[serde(rename = "sync_status", skip_serializing_if = "Option::is_none")]
    pub sync_status: Option<::models::SyncingStatus>,
}

impl InlineResponse200 {
    pub fn new() -> InlineResponse200 {
        InlineResponse200 {
            is_syncing: None,
            sync_status: None,
        }
    }
}


