mod attestation;
pub use self::attestation::Attestation;
mod attestation_data;
pub use self::attestation_data::AttestationData;
mod attester_slashings;
pub use self::attester_slashings::AttesterSlashings;
mod beacon_block;
pub use self::beacon_block::BeaconBlock;
mod beacon_block_all_of;
pub use self::beacon_block_all_of::BeaconBlockAllOf;
mod beacon_block_body;
pub use self::beacon_block_body::BeaconBlockBody;
mod beacon_block_common;
pub use self::beacon_block_common::BeaconBlockCommon;
mod beacon_block_header;
pub use self::beacon_block_header::BeaconBlockHeader;
mod beacon_block_header_all_of;
pub use self::beacon_block_header_all_of::BeaconBlockHeaderAllOf;
mod cross_link;
pub use self::cross_link::CrossLink;
mod deposit;
pub use self::deposit::Deposit;
mod deposit_data;
pub use self::deposit_data::DepositData;
mod eth1_data;
pub use self::eth1_data::Eth1Data;
mod fork;
pub use self::fork::Fork;
mod indexed_attestation;
pub use self::indexed_attestation::IndexedAttestation;
mod inline_response_200;
pub use self::inline_response_200::InlineResponse200;
mod inline_response_200_1;
pub use self::inline_response_200_1::InlineResponse2001;
mod proposer_slashings;
pub use self::proposer_slashings::ProposerSlashings;
mod syncing_status;
pub use self::syncing_status::SyncingStatus;
mod transfer;
pub use self::transfer::Transfer;
mod validator_duty;
pub use self::validator_duty::ValidatorDuty;
mod voluntary_exit;
pub use self::voluntary_exit::VoluntaryExit;
