/*
 * Minimal Beacon Node API for Validator
 *
 * A minimal API specification for the beacon node, which enables a validator to connect and perform its obligations on the Ethereum 2.0 phase 0 beacon chain.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProposerSlashings : The [`ProposerSlashing`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#proposerslashing) object from the Eth2.0 spec.

#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct ProposerSlashings {
    /// The index of the proposer to be slashed.
    #[serde(rename = "proposer_index", skip_serializing_if = "Option::is_none")]
    pub proposer_index: Option<i32>,
    #[serde(rename = "header_1", skip_serializing_if = "Option::is_none")]
    pub header_1: Option<::models::BeaconBlockHeader>,
    #[serde(rename = "header_2", skip_serializing_if = "Option::is_none")]
    pub header_2: Option<::models::BeaconBlockHeader>,
}

impl ProposerSlashings {
    /// The [`ProposerSlashing`](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#proposerslashing) object from the Eth2.0 spec.
    pub fn new() -> ProposerSlashings {
        ProposerSlashings {
            proposer_index: None,
            header_1: None,
            header_2: None,
        }
    }
}


