[package]
name = "lean_keystore"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "generate_keys"
path = "src/bin/generate_keys.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true, features = ["derive"] }
thiserror = "1"
hashsig = { git = "https://github.com/b-wagn/hash-sig", branch = "main" }
bincode = { workspace = true }
rand = "0.9"

[dev-dependencies]
tempfile = { workspace = true }
